appendCommitMessageToRunName: false

variables:
  - group: VG_${{ variables['Build.Repository.Name'] }}

trigger: none

resources:
  repositories:
    - repository: Apex_DevOps
      name: Apex/Apex_DevOps
      type: git
      ref: 'main'
  pipelines:
    - pipeline: ResourceDeployedToProd
      source: CERT_ReleaseCandidate_Apex_df-np-ea2-apex-pos-etl-int
      branch: releases/*
      trigger: none
      tags:
        - DeployedToPROD
      
      

extends:
  template: templates/extends/adf/CICD_Rollback.yml@Apex_DevOps
