appendCommitMessageToRunName: false

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
    - /

resources:
  repositories:
    - repository: Apex_DevOps
      name: Apex/Apex_DevOps
      type: git
      ref: 'main'

extends:
  template: templates/extends/adf/CICD_SyncBranchesWithMain.yml@Apex_DevOps
